### PR TITLE
removed full story script

### PR DESCRIPTION
**Pull request by xianc**
remove full story script which we want to stop using due to cost + have not made gdpr compliant

### CODE REVIEW

**Comment by hubt** [comment]
you probably @aeromusek to review this and not me.

**Comment by aeromusek** [comment]
@hubt this is one of those funky tools that we need your team to deploy 😬

**Comment by hubt** [comment]
I don't think I need to do anything special to deploy. just merge it to master to get it to staging(i'm not even sure if we have a staging for this), and then merge it to production to get it to prod.

If that doesn't work, we can take a look. @JaveriaK can help you out there if you need.

**Comment by aeromusek** [comment]
We definitely had deploy issues on at least a couple of these tools the last time an update like this needed to happen...so be prepared for a JIRA if/when this doesn't go through 😉 

@xianc let's give it a go!

**Comment by xianc** [comment]
merged! Let me know if there is any issues. The page looks good to me but I don't have a domain, apple app prefix & bundle id to double check with.

**Pull request merged**
